name: CI
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v3
      - run: cargo test --all --verbose

  format:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v3
      - run: cargo clippy --all -- -D warnings --verbose