name: Deploy WASM
on:
  workflow_run:
    branches: [main]
    workflows: [Continuous integration]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.4.0
      - uses: jetli/wasm-bindgen-action@v0.2.0

      - uses: actions/checkout@v3

      - run: trunk build --release

      - name: Upload WASM
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
      - name: Deploy GH Pages
        id: deployment
        uses: actions/deploy-pages@v2