name: Continuous integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v3
      - run: cargo test --all

  format:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v3
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v3
      - run: cargo clippy --all -- -D warnings